# Generated by Django 2.0.1 on 2018-04-14 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180414_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_of_both',
            new_name='date_of_birth',
        ),
    ]
